-- ============================================================================
-- Jobs and Applications (Migration 004)
-- ============================================================================
-- Jobs tables are not yet implemented in the database.
-- TODO: Define jobs, job_applications, job_views tables.
