-- ============================================================================
-- Payments and Notifications (Migration 006)
-- ============================================================================
-- Payment and notification tables are not yet implemented in the database.
-- TODO: Define payments, notifications, notification_preferences tables.
