// services/mockData.js
export const mockJobs = [
  {
    id: 1,
    title: "Senior React Developer",
    company: "TechNova AI",
    location: "Remote (Global)",
    workMode: "Remote",
    salary: "$130k – $160k",
    type: "Full-time",
    experience: "5–8 yrs",
    department: "Engineering",
    posted: "2 days ago",
    openings: 2,
    matchScore: 94,
    keySkillsMatched: ["React", "JavaScript", "Material UI", "Redux", "Frontend Architecture"],
    keySkillsMissing: ["GraphQL", "Next.js"],
    benefits: ["Equity", "Health Insurance", "$3k Learning Budget", "Unlimited PTO"],
    description: "TechNova AI is seeking a Senior React Developer to lead the frontend architecture of our next-generation AI platforms. You will work closely with our machine learning engineers to create intuitive, highly responsive dashboards.\n\nResponsibilities:\n• Architect and build scalable frontend applications using React\n• Mentor junior developers and establish best practices\n• Collaborate with design and product teams to ship high-quality features\n• Own performance monitoring and optimization\n\nRequirements:\n• 5+ years with React in production environments\n• Deep understanding of state management patterns\n• Excellent communication and leadership skills",
    logoColor: "#6366f1",
    about: "TechNova AI is a Series B startup building the next generation of AI-native productivity tools, trusted by 500+ enterprise teams worldwide."
  },
  {
    id: 2,
    title: "Frontend Engineer",
    company: "CreativeApp",
    location: "New York, NY",
    workMode: "Hybrid",
    salary: "$110k – $130k",
    type: "Full-time",
    experience: "2–4 yrs",
    department: "Product",
    posted: "1 week ago",
    openings: 3,
    matchScore: 85,
    keySkillsMatched: ["React", "CSS", "HTML"],
    keySkillsMissing: ["TypeScript"],
    benefits: ["Health Insurance", "401k Match", "Commuter Benefits"],
    description: "Join our creative team to build stunning user interfaces for our flagship product. You will be responsible for translating design wireframes into high-quality code and producing visual elements of the application.",
    logoColor: "#ec4899",
    about: "CreativeApp helps 2M+ creators monetize their work through our all-in-one platform."
  },
  {
    id: 3,
    title: "Full Stack Engineer",
    company: "FinanceFlow",
    location: "San Francisco, CA",
    workMode: "On-site",
    salary: "$150k – $180k",
    type: "Full-time",
    experience: "4–7 yrs",
    department: "Core Platform",
    posted: "3 days ago",
    openings: 1,
    matchScore: 78,
    keySkillsMatched: ["JavaScript", "React"],
    keySkillsMissing: ["Node.js", "PostgreSQL", "AWS"],
    benefits: ["Equity", "Health + Dental + Vision", "Free Meals", "Gym"],
    description: "FinanceFlow is revolutionizing fintech. We need a Full Stack Engineer comfortable with both React on the frontend and Node.js on the backend, building secure financial tools at scale.",
    logoColor: "#10b981",
    about: "FinanceFlow processes $2B+ in transactions annually for 10,000+ businesses."
  },
  {
    id: 4,
    title: "UI/UX Developer",
    company: "DesignCo",
    location: "Austin, TX",
    workMode: "Hybrid",
    salary: "$95k – $115k",
    type: "Contract",
    experience: "3–5 yrs",
    department: "Design Systems",
    posted: "5 days ago",
    openings: 2,
    matchScore: 88,
    keySkillsMatched: ["HTML", "CSS", "Material UI", "React"],
    keySkillsMissing: ["Figma", "Framer Motion"],
    benefits: ["Flexible Hours", "Remote Fridays", "Learning Stipend"],
    description: "We are looking for a UI/UX Developer who bridges the gap between design and technical implementation. Working alongside our design team, you will help create interactive and beautiful web experiences.",
    logoColor: "#f59e0b",
    about: "DesignCo is an award-winning digital product studio working with Fortune 500 brands."
  },
];

export const mockProfileData = {
  skills: "React, JavaScript, HTML, CSS, Material UI, Redux, Frontend Architecture",
  experience: "5 years",
  rolePreferences: "Frontend Developer, Senior Frontend Engineer",
  preferredLocation: "Remote, United States",
};
