import {
  FormControl,
  FormControlLabel,
  FormLabel,
  Grid,
  Radio,
  RadioGroup,
} from "@mui/material";
import ReactECharts from "echarts-for-react";
import React, { useEffect, useState } from "react";

export const GasPlantProductionChart = ({ rawData }) => {
  const [options, setOptions] = useState({});

  //   const rawData = [
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Condenstate",
  //       Month: "November",
  //       Year: 2023,
  //       Date: "2023-10-31T18:30:00.000Z",
  //       OpeningStockGallons: 0,
  //       ShrinkageGallons: 0,
  //       ReceiptsGallons: 0,
  //       ProductionGallons: 0,
  //       DeliveriesGallons: 0,
  //       ClosingStockGallons: 0,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Gasoline",
  //       Month: "November",
  //       Year: 2023,
  //       Date: "2023-10-31T18:30:00.000Z",
  //       OpeningStockGallons: 0,
  //       ShrinkageGallons: 0,
  //       ReceiptsGallons: 0,
  //       ProductionGallons: 76788.54,
  //       DeliveriesGallons: 0,
  //       ClosingStockGallons: 0,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Butane",
  //       Month: "November",
  //       Year: 2023,
  //       Date: "2023-10-31T18:30:00.000Z",
  //       OpeningStockGallons: 0,
  //       ShrinkageGallons: 0,
  //       ReceiptsGallons: 0,
  //       ProductionGallons: 107434.509,
  //       DeliveriesGallons: 0,
  //       ClosingStockGallons: 0,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Propane",
  //       Month: "November",
  //       Year: 2023,
  //       Date: "2023-10-31T18:30:00.000Z",
  //       OpeningStockGallons: 0,
  //       ShrinkageGallons: 0,
  //       ReceiptsGallons: 0,
  //       ProductionGallons: 223668.945,
  //       DeliveriesGallons: 0,
  //       ClosingStockGallons: 0,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "LPG",
  //       Month: "November",
  //       Year: 2023,
  //       Date: "2023-10-31T18:30:00.000Z",
  //       OpeningStockGallons: 0,
  //       ShrinkageGallons: 0,
  //       ReceiptsGallons: 0,
  //       ProductionGallons: 0,
  //       DeliveriesGallons: 0,
  //       ClosingStockGallons: 0,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Iso-Butane",
  //       Month: "November",
  //       Year: 2023,
  //       Date: "2023-10-31T18:30:00.000Z",
  //       OpeningStockGallons: 0,
  //       ShrinkageGallons: 0,
  //       ReceiptsGallons: 0,
  //       ProductionGallons: 0,
  //       DeliveriesGallons: 0,
  //       ClosingStockGallons: 0,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Ethane",
  //       Month: "November",
  //       Year: 2023,
  //       Date: "2023-10-31T18:30:00.000Z",
  //       OpeningStockGallons: 0,
  //       ShrinkageGallons: 0,
  //       ReceiptsGallons: 0,
  //       ProductionGallons: 358852.491,
  //       DeliveriesGallons: 0,
  //       ClosingStockGallons: 0,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Other",
  //       Month: "November",
  //       Year: 2023,
  //       Date: "2023-10-31T18:30:00.000Z",
  //       OpeningStockGallons: 0,
  //       ShrinkageGallons: 0,
  //       ReceiptsGallons: 0,
  //       ProductionGallons: 49.605,
  //       DeliveriesGallons: 0,
  //       ClosingStockGallons: 0,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Condenstate",
  //       Month: "December",
  //       Year: 2023,
  //       Date: "2023-11-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 0,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Gasoline",
  //       Month: "December",
  //       Year: 2023,
  //       Date: "2023-11-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 244734,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Butane",
  //       Month: "December",
  //       Year: 2023,
  //       Date: "2023-11-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 467208,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Propane",
  //       Month: "December",
  //       Year: 2023,
  //       Date: "2023-11-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 999558,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "LPG",
  //       Month: "December",
  //       Year: 2023,
  //       Date: "2023-11-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 0,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Iso-Butane",
  //       Month: "December",
  //       Year: 2023,
  //       Date: "2023-11-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 0,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Ethane",
  //       Month: "December",
  //       Year: 2023,
  //       Date: "2023-11-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 1538292,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Other",
  //       Month: "December",
  //       Year: 2023,
  //       Date: "2023-11-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 3780,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Condenstate",
  //       Month: "May",
  //       Year: 2024,
  //       Date: "2024-04-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Gasoline",
  //       Month: "May",
  //       Year: 2024,
  //       Date: "2024-04-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Butane",
  //       Month: "May",
  //       Year: 2024,
  //       Date: "2024-04-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Propane",
  //       Month: "May",
  //       Year: 2024,
  //       Date: "2024-04-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "LPG",
  //       Month: "May",
  //       Year: 2024,
  //       Date: "2024-04-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Iso-Butane",
  //       Month: "May",
  //       Year: 2024,
  //       Date: "2024-04-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Ethane",
  //       Month: "May",
  //       Year: 2024,
  //       Date: "2024-04-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Other",
  //       Month: "May",
  //       Year: 2024,
  //       Date: "2024-04-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Condenstate",
  //       Month: "March",
  //       Year: 2024,
  //       Date: "2024-02-29T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Gasoline",
  //       Month: "March",
  //       Year: 2024,
  //       Date: "2024-02-29T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Butane",
  //       Month: "March",
  //       Year: 2024,
  //       Date: "2024-02-29T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Propane",
  //       Month: "March",
  //       Year: 2024,
  //       Date: "2024-02-29T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "LPG",
  //       Month: "March",
  //       Year: 2024,
  //       Date: "2024-02-29T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Iso-Butane",
  //       Month: "March",
  //       Year: 2024,
  //       Date: "2024-02-29T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Ethane",
  //       Month: "March",
  //       Year: 2024,
  //       Date: "2024-02-29T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Other",
  //       Month: "March",
  //       Year: 2024,
  //       Date: "2024-02-29T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Condenstate",
  //       Month: "June",
  //       Year: 2024,
  //       Date: "2024-05-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Gasoline",
  //       Month: "June",
  //       Year: 2024,
  //       Date: "2024-05-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Butane",
  //       Month: "June",
  //       Year: 2024,
  //       Date: "2024-05-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Propane",
  //       Month: "June",
  //       Year: 2024,
  //       Date: "2024-05-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "LPG",
  //       Month: "June",
  //       Year: 2024,
  //       Date: "2024-05-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Iso-Butane",
  //       Month: "June",
  //       Year: 2024,
  //       Date: "2024-05-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Ethane",
  //       Month: "June",
  //       Year: 2024,
  //       Date: "2024-05-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Other",
  //       Month: "June",
  //       Year: 2024,
  //       Date: "2024-05-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Condenstate",
  //       Month: "July",
  //       Year: 2024,
  //       Date: "2024-06-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Gasoline",
  //       Month: "July",
  //       Year: 2024,
  //       Date: "2024-06-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Butane",
  //       Month: "July",
  //       Year: 2024,
  //       Date: "2024-06-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Propane",
  //       Month: "July",
  //       Year: 2024,
  //       Date: "2024-06-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "LPG",
  //       Month: "July",
  //       Year: 2024,
  //       Date: "2024-06-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Iso-Butane",
  //       Month: "July",
  //       Year: 2024,
  //       Date: "2024-06-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Ethane",
  //       Month: "July",
  //       Year: 2024,
  //       Date: "2024-06-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Other",
  //       Month: "July",
  //       Year: 2024,
  //       Date: "2024-06-30T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Condenstate",
  //       Month: "January",
  //       Year: 2024,
  //       Date: "2023-12-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 0,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Gasoline",
  //       Month: "January",
  //       Year: 2024,
  //       Date: "2023-12-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 240492,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Butane",
  //       Month: "January",
  //       Year: 2024,
  //       Date: "2023-12-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 459144,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Propane",
  //       Month: "January",
  //       Year: 2024,
  //       Date: "2023-12-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 982296,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "LPG",
  //       Month: "January",
  //       Year: 2024,
  //       Date: "2023-12-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 0,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Iso-Butane",
  //       Month: "January",
  //       Year: 2024,
  //       Date: "2023-12-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 0,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Ethane",
  //       Month: "January",
  //       Year: 2024,
  //       Date: "2023-12-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 1511706,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Other",
  //       Month: "January",
  //       Year: 2024,
  //       Date: "2023-12-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: 3696,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Condenstate",
  //       Month: "August",
  //       Year: 2024,
  //       Date: "2024-07-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Gasoline",
  //       Month: "August",
  //       Year: 2024,
  //       Date: "2024-07-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Butane",
  //       Month: "August",
  //       Year: 2024,
  //       Date: "2024-07-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Propane",
  //       Month: "August",
  //       Year: 2024,
  //       Date: "2024-07-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "LPG",
  //       Month: "August",
  //       Year: 2024,
  //       Date: "2024-07-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Iso-Butane",
  //       Month: "August",
  //       Year: 2024,
  //       Date: "2024-07-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Ethane",
  //       Month: "August",
  //       Year: 2024,
  //       Date: "2024-07-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Other",
  //       Month: "August",
  //       Year: 2024,
  //       Date: "2024-07-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Condenstate",
  //       Month: "April",
  //       Year: 2024,
  //       Date: "2024-03-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Gasoline",
  //       Month: "April",
  //       Year: 2024,
  //       Date: "2024-03-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Butane",
  //       Month: "April",
  //       Year: 2024,
  //       Date: "2024-03-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Propane",
  //       Month: "April",
  //       Year: 2024,
  //       Date: "2024-03-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "LPG",
  //       Month: "April",
  //       Year: 2024,
  //       Date: "2024-03-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Iso-Butane",
  //       Month: "April",
  //       Year: 2024,
  //       Date: "2024-03-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Ethane",
  //       Month: "April",
  //       Year: 2024,
  //       Date: "2024-03-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //     {
  //       GasPlant: "Tippett",
  //       City: "McCamey",
  //       County: "Crockett",
  //       State: "Texas",
  //       Basin: "Permian Basin",
  //       Operator: "Regency Field Services LLC",
  //       Owner: "Energy Transfer LP",
  //       Product: "Other",
  //       Month: "April",
  //       Year: 2024,
  //       Date: "2024-03-31T18:30:00.000Z",
  //       OpeningStockGallons: null,
  //       ShrinkageGallons: null,
  //       ReceiptsGallons: null,
  //       ProductionGallons: null,
  //       DeliveriesGallons: null,
  //       ClosingStockGallons: null,
  //     },
  //   ];

  const xKey = "Month";
  const yKeys = ["ProductionGallons"];

  const [products, setProducts] = useState([]);
  const [selectedproduct, setSelectedProduct] = useState("");

  const fnSelectProduct = (event) => {
    setSelectedProduct(event.target.value);
  };

  const fnGenerateChart = () => {
    const uniqueDates = [
      ...new Set(rawData.map((item) => `${item.Month}-${item.Year}`)),
    ];

    // Extract unique locations for series
    const uniqueFacilities = [...new Set(rawData.map((item) => item.GasPlant))];

    // Prepare series data
    const seriesData = uniqueFacilities.map((facility, index) => {
      const data = uniqueDates.map((date) => {
        const [month, year] = date.split("-");

        const entry = rawData.find(
          (item) =>
            item.Product === selectedproduct &&
            item.GasPlant === facility &&
            item.Month === month &&
            String(item.Year) === year
        );

        return entry && entry.ProductionGallons ? entry.ProductionGallons : 0; // Default to 0 if no data for date
      });

      return {
        name: facility,
        type: "line",
        data: data,
        markPoint: {
          data: [
            { type: "max", name: "Max" },
            { type: "min", name: "Min" },
          ],
        },
        markLine: {
          data: [{ type: "average", name: "Avg" }],
        },
        // yAxisIndex: index,
        yAxisIndex: 0,
      };
    });

    const chartoptions = {
      tooltip: {
        trigger: "axis",
      },
      legend: {
        data: uniqueFacilities, // Add legend for each location
        bottom: 0, // Moves the legend to the bottom
      },
      toolbox: {
        show: true,
        feature: {
          dataZoom: {
            yAxisIndex: "none",
          },
          dataView: { readOnly: false },
          magicType: { type: ["line", "bar"] },
          restore: {},
          saveAsImage: {},
        },
      },
      xAxis: {
        type: "category", // Changed type to category
        boundaryGap: false,
        data: uniqueDates, // Set x-axis dates
      },

      yAxis: {
        type: "value",
        position: "left",
        axisLine: {
          lineStyle: {
            color: "#1890FF", // Primary Y-axis color
          },
        },
      },
      series: seriesData, // Add series data
    };

    setOptions(chartoptions);
  };

  useEffect(() => {
    if (selectedproduct !== "") {
      fnGenerateChart();
    }
  }, [selectedproduct]);

  useEffect(() => {
    if (rawData.length > 0) {
      const uniqueProducts = [...new Set(rawData.map((item) => item.Product))];

      setProducts(uniqueProducts);
      setSelectedProduct(uniqueProducts[0]);

      // Prepare series data with multiple stacks by Location
      // const seriesData = uniqueFacilities.flatMap((facility) =>
      //   uniqueProducts.map((product) => ({
      //     name: `${product} (${facility})`, // Legend Label
      //     type: "bar",
      //     stack: facility, // Stack all Products under the same Location
      //     data: uniqueDates.map((date) => {
      //       const [month, year] = date.split("-");
      //       const entry = rawData.find(
      //         (item) =>
      //           item.Product === product &&
      //           item.GasPlant === facility &&
      //           item.Month === month &&
      //           String(item.Year) === year
      //       );
      //       return entry ? entry.ProductionGallons : 0;
      //     }),
      //   }))
      // );

      // ECharts options
      // const chartoptions = {
      //   tooltip: { trigger: "axis", axisPointer: { type: "shadow" } },
      //   // legend: { data: seriesData.map((item) => item.name), bottom: 0 },
      //   xAxis: { type: "category", data: uniqueDates },
      //   yAxis: { type: "value" },
      //   series: seriesData,
      // };

      //   //For Single Facility
      //   const seriesData = uniqueProducts.map((product) => ({
      //     name: product,
      //     type: "bar",
      //     stack: "total", // Enables stacking
      //     data: uniqueDates.map((date) => {
      //       const [month, year] = date.split("-");
      //       const entry = rawData.find(
      //         (item) =>
      //           item.Product === product &&
      //           item.Month === month &&
      //           String(item.Year) === year
      //       );
      //       return entry ? entry.ProductionGallons : 0;
      //     }),
      //   }));

      //   //For Single Facility
      //   const chartoptions = {
      //     tooltip: { trigger: "axis", axisPointer: { type: "shadow" } },
      //     legend: { data: uniqueProducts, bottom: 0 },
      //     xAxis: { type: "category", data: uniqueDates },
      //     yAxis: { type: "value" },
      //     series: seriesData,
      //   };
    }
  }, [rawData]);

  return (
    <>
      {rawData.length > 0 && selectedproduct !== "" && (
        <Grid
          container
          direction="row"
          sx={{
            justifyContent: "space-evenly",
            alignItems: "center",
          }}
        >
          <Grid size={3} item>
            {products.length > 0 && selectedproduct !== "" && (
              <>
                <FormControl>
                  <FormLabel id="gasplantproductsid">Product</FormLabel>
                  <RadioGroup
                    aria-labelledby="gasplantproductsid"
                    defaultValue={selectedproduct}
                    name="GasPlantProducts"
                    onChange={fnSelectProduct}
                    value={selectedproduct}
                  >
                    {products.map((product) => (
                      <FormControlLabel
                        value={product}
                        control={<Radio />}
                        label={product}
                      />
                    ))}
                  </RadioGroup>
                </FormControl>
              </>
            )}
          </Grid>
          <Grid size={9} item>
            <ReactECharts
              style={{ minWidth: "145vh", minHeight: "70vh" }}
              option={options}
            />
          </Grid>
        </Grid>
      )}
    </>
  );
};
